<ul id="tabs" class="nav nav-tabs">
	<li class="active"><a href="#personal_information" data-toggle="tab">Personal Information</a></li>
	<li><a href="#address" data-toggle="tab">Address</a></li>
	<li><a href="#contact" data-toggle="tab">Contact</a></li>
	<li><a href="#demographics" data-toggle="tab">Demographics</a></li>
	<li><a href="#geography" data-toggle="tab">Geography</a></li>
	<li><a href="#language" data-toggle="tab">Language</a></li>
	<li><a href="#citizenship" data-toggle="tab">Citizenship</a></li>
</ul>
<div class="tab-content">
	<div id="personal_information" class="tab-pane active">
		<spine::personal_information/>
	</div>
	<div id="address" class="tab-pane">
		<spine::address/>
	</div>
	<div id="contact" class="tab-pane">
		<spine::contact_details/>
	</div>
	<div id="demographics" class="tab-pane">
		<spine::demographics/>
	</div>
	<div id="geography" class="tab-pane">
		<spine::geography/>
	</div>
	<div id="language" class="tab-pane">
		<spine::language/>
	</div>
	<div id="citizenship" class="tab-pane">
		<spine::citizenship/>
	</div>
</div>
