<ul id="tabs" class="nav nav-tabs">
	<li class="active"><a href="#personal_essay" data-toggle="tab">Personal Essay</a></li>
	<li><a href="#discplinary_history" data-toggle="tab">Disciplinary History</a></li>
	<li><a href="#additional_information" data-toggle="tab">Additional Information</a></li>
</ul>
<div class="tab-content">
	<div id="personal_essay" class="tab-pane active">
		<spine::personal_essay/>
	</div>
	<div id="discplinary_history" class="tab-pane">
		<spine::disciplinary_history/>
	</div>
	<div id="additional_information" class="tab-pane">
		<spine::additional_information/>
	</div>
</div>
