<div>
	<form name="add_payment">
		<div>
			<div><span>First Name</span></div>
			<input type="text" name="firstname" placeholder="First Name" />
			<div><span>Middle Name</span></div>
			<input type="text" name="middlename" placeholder="Middle Name" />
			<div><span>Last Name</span></div>
			<input type="text" name="lastname" placeholder="Last Name" />
			<div><span>Email Address</span></div>
			<input type="text" name="email" placeholder="Email Address" />
			<div><span>Contact No.</span></div>
			<input type="text" name="contactnumber" placeholder="Contact Number" />
			<div><span>O.R. Number</span></div>
			<input type="text" name="or_number" placeholder="O.R. Number" />
			<div><input type="submit" /></div>
		</div>
	</form>
</div>