<div id="loginContainer">
<img src="/counselor/views/main/images/logo/logo.svg" class="mBm" alt="Educounsel" title="Educounsel"/>
	<form action="/user/login" method="POST">
		<input type="text" placeholder="Username" name="username" id="username"/><br/>
	    <input type="password" placeholder="Password" name="password" id="password"/><br/>
	    <input type="submit" name="submit" value="Log In"/>
	</form>
</div>