<div class="row header">
	<div class="navbar navbar-fixed-top span12">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">SPINE-FM</a>
			<ul class="nav">
				<li class="<?php $this->isActive('dashboard');?>"><a href="/<?=SITE?>/dashboard">Dashboard</a></li>
				<li class="<?php $this->isActive('counselors');?>"><a href="/<?=SITE?>/counselors">Counselors</a></li>
				<li class="<?php $this->isActive('payment');?>"><a href="/<?=SITE?>/payment">Payment</a></li>
			</ul>
		</div>
	</div>
	</div>
</div>
<span class="clearfix"></span>
