<div class="row header">
	<div class="navbar navbar-fixed-top span12">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">SPINE-FM</a>
			<ul class="nav">
				<li class="<?php $this->isActive('home');?>"><a href="/home">Home</a></li>
				<li class="<?php $this->isActive('about');?>"><a href="/about-us">About</a></li>
				<li class="<?php $this->isActive('contact');?>"><a href="/contact-us">Contact Us</a></li>
			</ul>
		</div>
	</div>
	</div>
</div>
<span class="clearfix"></span>
