<div class="sectionContainer" data-column="testing" data-section_name="act_tests">
	<div>
		<b>ACT Tests</b>
	</div>
	
	<div>
		<span class="clearfix">Number of ACT you have taken the ACT*?</span>
		<?php echo htmlRenderer::makeSelectInput(range(0, 10), "number_of_act", "", isset($act_tests["number_of_act"]) ? $act_tests["number_of_act"] : "", "selectCounter conditionalQuestionForSelect")?>
	</div>
	
	<!-- conditional divs for 0 -->
	<?php (isset($act_tests["number_of_act"]) && $act_tests["number_of_act"] == "0")? $class="" : $class="hide";?>
	<div class="number_of_act <?php echo $class?>" data-answer="0">
		<span class="clearfix">Future Testing Date</span>
		<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("months"), "testing_date_months", "Select Months", isset($act_tests["testing_date_months"]) ? $act_tests["testing_date_months"] : "")?>
		<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("years"), "testing_date_years", "YYYY", isset($act_tests["testing_date_years"]) ? $act_tests["testing_date_years"] : "")?>
	</div>
	
	<div id="number_of_act">
	<?php (isset($act_tests["number_of_act"]))? $counter = $act_tests["number_of_act"] :  $counter = 0;?>
	<?php for($i=1; $i<=7; $i++):?>
	<?php ($counter < $i)? $class = "hide" : $class = ""; ?>
	<div id="number_of_act_container<?php echo $i?>" class="<?php echo $class?>">
		<hr />
		<div>
			<span class="clearfix">Highest composite score?*</span>
			<?php echo htmlRenderer::makeSelectInput(range(30, 50), "highest_composite_score$i", "", isset($act_tests["highest_composite_score$i"]) ? $act_tests["highest_composite_score$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">Coposite Date?*</span>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("months"), "composite_date_months$i", "Select Months", isset($act_tests["composite_date_months$i"]) ? $act_tests["composite_date_months$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(range(1, 31), "composite_date_days$i", "dd", isset($act_tests["composite_date_days$i"]) ? $act_tests["composite_date_days$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("years"), "composite_date_years$i", "YYYY", isset($act_tests["composite_date_years$i"]) ? $act_tests["composite_date_years$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">Highest englsih score?*</span>
			<?php echo htmlRenderer::makeSelectInput(range(30, 50), "highest_english_score$i", "", isset($act_tests["highest_english_score$i"]) ? $act_tests["highest_english_score$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">English Date?*</span>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("months"), "english_date_months$i", "Select Months", isset($act_tests["english_date_months$i"]) ? $act_tests["english_date_months$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(range(1, 31), "english_date_days$i", "dd", isset($act_tests["english_date_days$i"]) ? $act_tests["english_date_days$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("years"), "english_date_years$i", "YYYY", isset($act_tests["english_date_years$i"]) ? $act_tests["english_date_years$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">Highest englsih score?*</span>
			<?php echo htmlRenderer::makeSelectInput(range(30, 50), "highest_writing_score$i", "", isset($act_tests["highest_writing_score$i"]) ? $act_tests["highest_writing_score$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">writing Date?*</span>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("months"), "writing_date_months$i", "Select Months", isset($act_tests["writing_date_months$i"]) ? $act_tests["writing_date_months$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(range(1, 31), "writing_date_days$i", "dd", isset($act_tests["writing_date_days$i"]) ? $act_tests["writing_date_days$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("years"), "writing_date_years$i", "YYYY", isset($act_tests["writing_date_years$i"]) ? $act_tests["writing_date_years$i"] : "")?>
		</div>
	</div>
	<?php endfor?>
	</div>	
</div>
