<div class="sectionContainer" data-column="testing" data-section_name="senior_secondary_leaving_examination">
	<div>
		<b>senior Subject Tests</b>
	</div>
	
	<div>
		<span class="clearfix">Number of senior Subject Test you wish to report, including tests you epect to take*?</span>
		<?php echo htmlRenderer::makeSelectInput(range(0, 10), "number_of_senior_subject", "", isset($senior_secondary_leaving_examination["number_of_senior_subject"]) ? $senior_secondary_leaving_examination["number_of_senior_subject"] : "", "selectCounter")?>
	</div>

	<div id="number_of_senior_subject">
	<?php (isset($senior_secondary_leaving_examination["number_of_senior_subject"]))? $counter = $senior_secondary_leaving_examination["number_of_senior_subject"] :  $counter = 0;?>
	<?php for($i=1; $i<=7; $i++):?>
	<?php ($counter < $i)? $class = "hide" : $class = ""; ?>
	<div id="number_of_senior_subject_container<?php echo $i?>" class="<?php echo $class?>">
		<hr />
		<div>
			<span class="clearfix">Date taken or planned?*</span>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("months"), "date_taken_months$i", "Select Months", isset($senior_secondary_leaving_examination["date_taken_months$i"]) ? $senior_secondary_leaving_examination["date_taken_months$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("years"), "date_taken_years$i", "YYYY", isset($senior_secondary_leaving_examination["date_taken_years$i"]) ? $senior_secondary_leaving_examination["date_taken_years$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">Subject?*</span>
			<?php $values = array("Chemistry","English", "Math")?>
			<?php echo htmlRenderer::makeSelectInput($values, "subject$i", "", isset($senior_secondary_leaving_examination["subject$i"]) ? $senior_secondary_leaving_examination["subject$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">Score</span>
			<?php echo htmlRenderer::makeSelectInput(range(800, 850), "score$i", "", isset($senior_secondary_leaving_examination["score$i"]) ? $senior_secondary_leaving_examination["score$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">Score Type</span>
			<?php echo htmlRenderer::makeSelectInput(array("Actual", "Predicted"), "score_type$i", "", isset($senior_secondary_leaving_examination["score_type$i"]) ? $senior_secondary_leaving_examination["score_type$i"] : "")?>
		</div>
	</div>
	<?php endfor?>
	</div>	
</div>
