<ul id="tabs" class="nav nav-tabs">
	<li class="active"><a href="#tests_taken" data-toggle="tab">Tests Taken</a></li>
	<li><a href="#act_tests" data-toggle="tab">Act Tests</a></li>
	<li><a href="#sat_tests" data-toggle="tab">Sat Tests</a></li>
	<li><a href="#sat_subject_tests" data-toggle="tab">Sat Subject Tests</a></li>
	<li><a href="#ap_subject_tests" data-toggle="tab">AP Subject Tests</a></li>
	<li><a href="#ib_subject_tests" data-toggle="tab">IB Subject Tests</a></li>
	<li><a href="#senior_secondary_leaving_examination" data-toggle="tab">Senior Secondary Leaving Examination</a></li>
	<li><a href="#toefl_ibt" data-toggle="tab">TOEFL IBT</a></li>
	<li><a href="#toefl_paper" data-toggle="tab">TOEFL Paper</a></li>
	<li><a href="#pte_academic_tests" data-toggle="tab">PTE Academic Tests</a></li>
	<li><a href="#ielst" data-toggle="tab">IELST</a></li>
</ul>

<div class="tab-content">
	<div id="tests_taken" class="tab-pane active">
		<spine::tests_taken/>
	</div>
	<div id="act_tests" class="tab-pane">
		<spine::act_tests/>
	</div>
	<div id="sat_tests" class="tab-pane">
		<spine::sat_tests/>
	</div>
	<div id="sat_subject_tests" class="tab-pane">
		<spine::sat_subject_tests/>
	</div>
	<div id="ap_subject_tests" class="tab-pane">
		<spine::ap_subject_tests/>
	</div>
	<div id="ib_subject_tests" class="tab-pane">
		<spine::ib_subject_tests/>
	</div>
	<div id="senior_secondary_leaving_examination" class="tab-pane">
		<spine::senior_secondary_leaving_examination/>
	</div>
	<div id="toefl_ibt" class="tab-pane">
		<spine::toefl_ibt/>
	</div>
	<div id="toefl_paper" class="tab-pane">
		<spine::toefl_paper/>
	</div>
	<div id="pte_academic_tests" class="tab-pane">
		<spine::pte_academic_tests/>
	</div>
	<div id="ielst" class="tab-pane">
		<spine::ielst/>
	</div>
</div>
