<div class="sectionContainer" data-column="testing" data-section_name="toefl_ibt">
	<div>
		<b>toefl Tests</b>
	</div>
	
	<div>
		<span class="clearfix">Number of times  you have taken the toefl*?</span>
		<?php echo htmlRenderer::makeSelectInput(range(0, 10), "number_of_toefl", "", isset($toefl_ibt["number_of_toefl"]) ? $toefl_ibt["number_of_toefl"] : "", "selectCounter conditionalQuestionForSelect")?>
	</div>
	
	<!-- conditional divs for 0 -->
	<?php (isset($toefl_ibt["number_of_toefl"]) && $toefl_ibt["number_of_toefl"] == "0")? $class="" : $class="hide";?>
	<div class="number_of_toefl <?php echo $class?>" data-answer="0">
		<span class="clearfix">Future Testing Date</span>
		<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("months"), "testing_date_months", "Select Months", isset($toefl_ibt["testing_date_months"]) ? $toefl_ibt["testing_date_months"] : "")?>
		<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("years"), "testing_date_years", "YYYY", isset($toefl_ibt["testing_date_years"]) ? $toefl_ibt["testing_date_years"] : "")?>
	</div>
	
	<div id="number_of_toefl">
	<?php (isset($toefl_ibt["number_of_toefl"]))? $counter = $toefl_ibt["number_of_toefl"] :  $counter = 0;?>
	<?php for($i=1; $i<=7; $i++):?>
	<?php ($counter < $i)? $class = "hide" : $class = ""; ?>
	<div id="number_of_toefl_container<?php echo $i?>" class="<?php echo $class?>">
		<hr />
		<div>
			<span class="clearfix">Highest critical score?*</span>
			<?php echo htmlRenderer::makeSelectInput(range(30, 50), "highest_critical_score$i", "", isset($toefl_ibt["highest_critical_score$i"]) ? $toefl_ibt["highest_critical_score$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">Critial Reading Date?*</span>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("months"), "critical_date_months$i", "Select Months", isset($toefl_ibt["critical_date_months$i"]) ? $toefl_ibt["critical_date_months$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(range(1, 31), "critical_date_days$i", "dd", isset($toefl_ibt["critical_date_days$i"]) ? $toefl_ibt["critical_date_days$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("years"), "critical_date_years$i", "YYYY", isset($toefl_ibt["critical_date_years$i"]) ? $toefl_ibt["critical_date_years$i"] : "")?>
		</div>
		
		<div>
			<span class="clearfix">Highest match score?*</span>
			<?php echo htmlRenderer::makeSelectInput(range(30, 50), "highest_match_score$i", "", isset($toefl_ibt["highest_match_score$i"]) ? $toefl_ibt["highest_match_score$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">match Date?*</span>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("months"), "match_date_months$i", "Select Months", isset($toefl_ibt["match_date_months$i"]) ? $toefl_ibt["match_date_months$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(range(1, 31), "match_date_days$i", "dd", isset($toefl_ibt["match_date_days$i"]) ? $toefl_ibt["match_date_days$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("years"), "match_date_years$i", "YYYY", isset($toefl_ibt["match_date_years$i"]) ? $toefl_ibt["match_date_years$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">Highest writing score?*</span>
			<?php echo htmlRenderer::makeSelectInput(range(30, 50), "highest_writing_score$i", "", isset($toefl_ibt["highest_writing_score$i"]) ? $toefl_ibt["highest_writing_score$i"] : "")?>
		</div>
		<div>
			<span class="clearfix">writing Date?*</span>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("months"), "writing_date_months$i", "Select Months", isset($toefl_ibt["writing_date_months$i"]) ? $toefl_ibt["writing_date_months$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(range(1, 31), "writing_date_days$i", "dd", isset($toefl_ibt["writing_date_days$i"]) ? $toefl_ibt["writing_date_days$i"] : "")?>
			<?php echo htmlRenderer::makeSelectInput(htmlRenderer::getArrayItems("years"), "writing_date_years$i", "YYYY", isset($toefl_ibt["writing_date_years$i"]) ? $toefl_ibt["writing_date_years$i"] : "")?>
		</div>
	</div>
	<?php endfor?>
	</div>	
</div>
