<div class="container mVl">
	<div class="row">
		<div id="calendar" class="col-xs-12"></div>
		<input type="hidden" class="hide" id="new_event_id_temp_holder" />
	</div>
</div>
<div class="modal fade" id="modal_saving_ajax" data-backdrop="static">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <p id="status_message">Saving...</p>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<spine::add_modal/>
<spine::edit_modal/>
<spine::edit_gui/>