<div>
	<form name="add_payment">
		<div>
			<div><span>First Name</span></div>
			<input type="text" name="first_name" placeholder="First Name" />
			<div><span>Middle Name</span></div>
			<input type="text" name="middle_name" placeholder="Middle Name" />
			<div><span>Last Name</span></div>
			<input type="text" name="last_name" placeholder="Last Name" />
			<hr/>
			<div><span>Email Address</span></div>
			<input type="text" name="email" placeholder="Email Address" />
			<div><span>Contact No.</span></div>
			<input type="text" name="contact_number" placeholder="Contact Number" />
			<hr/>
			<div><span>Amount</span></div>
			<input type="text" name="amount" placeholder="Amount" />
			<div><span>O.R. Number</span></div>
			<input type="text" name="or_number" placeholder="O.R. Number" />
			<div><span>Credit(s)</span></div>
			<input type="text" name="credits" placeholder="Number of Credits"/>
			<div><input type="submit" /></div>
		</div>
	</form>
</div>