<div class="accountPanel clearfix">
	<span class="profileImage mRm fleft" style="background-image:url('data:image/jpg;JPEG;gif;png;base64,<?=$data['photo']?>');"></span>
	<p>Account Settings</p>
	<a href="/user/edit-profile">Edit Profile</a>
	<a href="#" title="Logout">Log out</a>
	<!-- <img src="data:image/jpg;JPEG;gif;png;base64,<?//=$data['photo']?>">  -->
	<!--<span><?//=$data['username']?></span><br/>
	<span><?//=ucwords($data['firstname'])?> <?=ucwords($data['lastname'])?></span><br/>
	<span><?//=$data['email_address']?></span><br/>
	-->
</div>