<div class="col-xs-12">
	<ul id="collegesTab" class="tabs">
		<?foreach ($alphabet as $alpha_char):?>
			<li><a href="<?='#'.strtolower($alpha_char)?>" data-toggle="tab"><?=$alpha_char?></a></li>			
		<?endforeach;?>
	</ul>
	<div class="tab-content clearfix">
		<? foreach ($colleges as $colleges_index => $college ):?>
			<div id="<?=strtolower($colleges_index)?>" class="tab-pane">
				<!-- <h3><?//=$colleges_index?></h3>  -->
				<? ksort($college);?>
				<? foreach ($college as $college_index => $college_info):?>
					<span><a href="/colleges/profile/cc/<?=$college_info['college_code']?>"><?=$college_index?></a></span><br/>
				<? endforeach;?>
			</div>
		<? endforeach;?>
	</div>
</div>
