<div class="container">
	<span><a href="http://<?=$email_address?>" target="_blank">Go to Official Website</a></span>
	<div class="row-fluid">
	<ul id="tab">
		<li><a href="#sample1" data-toggle="tab">sample 1</a></li>
		<li><a href="#sample2" data-toggle="tab">sample 2</a></li>
		<li><a href="#sample3" data-toggle="tab">sample 3</a></li>
	</ul>
	<div class="tab-content">
		<?=$college_profile?>
	</div>
	</div>
</div>


