<input type="hidden" name="user_id" value="1" />
<div class="row content">
	<div class="container">
		<div class="row-fluid" style="float:left;">
			<div class="span2">
				<spine::side_navigation/>
			</div>
			<div class="span10 tab-content">
				<div id="profile_container" class="tab-pane active">
					<spine::profile_container/>
				</div>
				<div id="family_container" class="tab-pane">
					<spine::family_container/>
				</div>
				<div id="education_container" class="tab-pane">
					<spine::education_container/>
				</div>
				<div id="testing_container" class="tab-pane">
					<spine::testing_container/>
				</div>
				<div id="writing_container" class="tab-pane">
					<spine::writings_container/>
				</div>
			</div>
		</div>	
		
	</div>
</div>




