<ul id="mainSection" class="fleft nav" style="float:left;">
	<li class="active"><a href="#profile_container" data-toggle="tab">Profile</a></li>
	<li><a href="#family_container" data-toggle="tab">Family</a></li>
	<li><a href="#education_container" data-toggle="tab">Education</a></li>
	<li><a href="#testing_container" data-toggle="tab">Testing</a></li>
	<li><a href="#activities_container" data-toggle="tab">Activities</a></li>
	<li><a href="#writing_container" data-toggle="tab">Writing</a></li>
</ul>