<ul id="tabs" class="nav nav-tabs">
	<li class="active"><a href="#household" data-toggle="tab">Household</a></li>
	<li><a href="#parent1" data-toggle="tab">Parent 1</a></li>
	<li><a href="#parent2" data-toggle="tab">Parent 2</a></li>
	<li><a href="#legal_guardian" data-toggle="tab">Legal Guardian</a></li>
	<li><a href="#siblings" data-toggle="tab">Siblings</a></li>
</ul>
<div class="tab-content">
	<div id="household" class="tab-pane active">
		<spine::household/>
	</div>
	<div id="parent1" class="tab-pane">
		<spine::parent1/>
	</div>
	<div id="parent2" class="tab-pane">
		<spine::parent2/>
	</div>
	<div id="legal_guardian" class="tab-pane">
		<spine::legal_guardian/>
	</div>
	<div id="siblings" class="tab-pane">
		<spine::siblings/>
	</div>
</div>

