<div class="sectionContainer" data-column="education" data-section_name="current_year_courses">
	<div>
		<b>Current Year Courses</b>
	</div>

	<div>
		<span class="clearfix">How many courses would you like to report?</span>
		<?php echo htmlRenderer::makeSelectInput(range(0, 10), "number_of_courses", "", isset($current_year_courses["number_of_courses"]) ? $current_year_courses["number_of_courses"] : "", "selectCounter")?>
	</div>
	
	<div id="number_of_courses">
	<?php (isset($current_year_courses["number_of_courses"]))? $counter = $current_year_courses["number_of_courses"] :  $counter = 0;?>
	<?php for($i=1; $i<=7; $i++):?>
	<?php ($counter < $i)? $class = "hide" : $class = ""; ?>
	<div id="number_of_courses_container<?php echo $i?>" class="<?php echo $class?>">
		<hr />
			
		<div>
			<span class="clearfix">Course Title</span>
			<input type="text" name="course_title<?php echo $i?>"  value="<?php echo isset($current_year_courses["course_title$i"]) ? $current_year_courses["course_title$i"] : ""; ?>" />
		</div>
		
		<div>
			<span class="clearfix">Course level, if applicable</span>
			<?php $values = array("Accelerated", "Advance Placement(AP)", "Honors", "International Bacallaureate(IB)", "Regents");?>
			<?php echo htmlRenderer::makeSelectInput($values, "course_level$i", "Select prefix", isset($current_year_courses["course_level$i"]) ? $current_year_courses["course_level$i"] : "")?>
		</div>
		
		<div>
			<span class="clearfix">Course credit value</span>
			<input type="text" name="course_credit_value<?php echo $i?>"  value="<?php echo isset($current_year_courses["course_credit_value$i"]) ? $current_year_courses["course_credit_value$i"] : ""; ?>" />
		</div>
		
		<div>
			<input type="checkbox" <?php echo (isset($current_year_courses["full_year$i"]) && $current_year_courses["full_year$i"]  != "" )? "checked" : ""; ?> value="Full Year" name="full_year<?php echo $i?>" />
			<span>Full Year</span>
		</div>
		
		<div>
			<input type="checkbox" <?php echo (isset($current_year_courses["first_semester$i"]) && $current_year_courses["first_semester$i"]  != "" )? "checked" : ""; ?> value="First Semester" name="first_semester<?php echo $i?>" />
			<span>Full Semester</span>
		</div>

		<div>
			<input type="checkbox" <?php echo (isset($current_year_courses["first_trimester$i"]) && $current_year_courses["first_trimester$i"]  != "" )? "checked" : ""; ?> value="First Trimester" name="first_trimester<?php echo $i?>" />
			<span>Full Trimester</span>
		</div>

		<div>
			<input type="checkbox" <?php echo (isset($current_year_courses["second_semester$i"]) && $current_year_courses["second_semester$i"]  != "" )? "checked" : ""; ?> value="Second Semester" name="second_semester<?php echo $i?>" />
			<span>Second Semester</span>
		</div>

		<div>
			<input type="checkbox" <?php echo (isset($current_year_courses["second_trimester$i"]) && $current_year_courses["second_trimester$i"]  != "" )? "checked" : ""; ?> value="Second Trimester" name="second_trimester<?php echo $i?>" />
			<span>Second Trimester</span>
		</div>
		
		<div>
			<input type="checkbox" <?php echo (isset($current_year_courses["third_trimester$i"]) && $current_year_courses["third_trimester$i"]  != "" )? "checked" : ""; ?> value="Third Trimester" name="third_trimester<?php echo $i?>" />
			<span>Third Trimester</span>
		</div>
		
		
	</div>
	<?php endfor?>
	</div>	
	
</div>
