<ul id="tabs" class="nav nav-tabs">
	<li class="active"><a href="#school" data-toggle="tab">School</a></li>
	<li><a href="#other_school" data-toggle="tab">Other School</a></li>
	<li><a href="#education_interruption" data-toggle="tab">Education Interruption</a></li>
	<li><a href="#college_and_universities" data-toggle="tab">College & Universities</a></li>
	<li><a href="#cbo" data-toggle="tab">CBO</a></li>
	<li><a href="#grades" data-toggle="tab">Grades</a></li>
	<li><a href="#current_year_courses" data-toggle="tab">Current Year Courses</a></li>
	<li><a href="#honors" data-toggle="tab">Honors</a></li>
	<li><a href="#future_plans" data-toggle="tab">Future Plans</a></li>
</ul>

<div class="tab-content">
	<div id="school" class="tab-pane active">
		<spine::school/>
	</div>
	<div id="other_school" class="tab-pane">
		<spine::other_school/>
	</div>
	<div id="education_interruption" class="tab-pane">
		<spine::education_interruption/>
	</div>
	<div id="college_and_universities" class="tab-pane">
		<spine::college_and_universities/>
	</div>
	<div id="cbo" class="tab-pane active">
		<spine::cbo/>
	</div>
	<div id="grades" class="tab-pane active">
		<spine::grades/>
	</div>
	<div id="current_year_courses" class="tab-pane">
		<spine::current_year_courses/>
	</div>
	<div id="honors" class="tab-pane">
		<spine::honors/>
	</div>
	<div id="future_plans" class="tab-pane">
		<spine::future_plans/>
	</div>
</div>

